version: '3'

services:
  app:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: snupie_bd
      DB_USER: myuser
      DB_PASSWORD: secret
    ports:
      - 5000:5000
    networks:
      - web
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    command: npm start

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: myuser
      MYSQL_PASSWORD: secret
    networks:
      - web
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/
    ports:
      - "3307:3306"  # Corregido el mapeo de puertos

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
    networks:
      - web
    ports:
      - "8080:80"
    depends_on:
      - db

networks:
  web:
    driver: bridge
